Desktop/weekend-blog-master/blogs/urls.py
from django.conf.urls import url
from .views import blog_list, blog_create, blog_update

urlpatterns = [

    url(r'^list/', blog_list, name='list'),
    url(r'^create/', blog_create, name='create'),
    url(r'^(?P<pk>\d+)/update/', blog_update, name='update'),
]

Desktop/weekend-blog-master/weekend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
url(r'^$', TemplateView.as_view(template_name='base.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
]

Desktop/weekend-blog-master/blogs/models.py
from django.db import models


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Desktop/weekend-blog-master/blogs/forms.py
from django.forms import ModelForm

from .models import Blog

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = [
            'title',
            'content',
        ]

Desktop/weekend-blog-master/blogs/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

from .models import Blog
from .forms import BlogForm


# CRUD
# Create your views here.


def blog_list(request):
    queryset = Blog.objects.all()
    context = {
        'object_list': queryset,
    }

    return render(request, 'blogs/list.html', context)


def blog_create(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('blogs:list'))
    else:
        form = BlogForm()

    context = {
        'form': form,
    }

    return render(request, 'blogs/create.html', context)


def blog_update(request, pk=None):
    instance = Blog.objects.get(pk=pk)
    form = BlogForm(request.POST, instance=instance)
    if form.is_valid():
        instance.save()
        return HttpResponseRedirect(reverse('blogs:list'))

    context = {
        'form': form,
    }

    return render(request, 'blogs/update.html', context)

Desktop/weekend-blog-master/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Blog App{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">

    <link type="text/css" rel="stylesheet" href="css/style.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


</head>

<body>

<nav>
    <div class="nav-wrapper teal lighten-2">
        <a href="#" class="brand-logo">Ducat Python : June 17</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if request.user.is_authenticated %}
            <li><a href="#">{{ request.user.username }}</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
                <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}



<br><br><br><br><br>
<footer class="page-footer teal lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer
                    content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>


<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>
</body>
</html>

Desktop/weekend-blog-master/templates/blogs/create.html
{% extends 'base.html' %}



{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create Post">
</form>


{% endblock %}

Desktop/weekend-blog-master/templates/blogs/list.html
{% extends 'base.html' %}


{% block content %}


    <div class="container">
        <div class="row">
            {% for object in object_list %}
                <div class="col s6">

                    <h5>{{ object.title }}</h5>
                    <p>{{ object.content }}</p>
                    <a class="btn" href="{% url 'blogs:update' object.pk %}">Update</a>

                </div>

            {% endfor %}
        </div>
    </div>

    <a  class="btn blue" href="{% url 'blogs:create' %}">Click to Create new blog</a>

{% endblock %}

Desktop/weekend-blog-master/templates/blogs/update.html
{%  extends 'base.html' %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create Post">
</form>

{% endblock %}